# REPLACE PROJECT NAME
PROJ_NAME="PROJ"

# SET UP PROJECT LOCATION
PROJ_FOLDER=./PROJ-TEST

# YOU CAN CHANGE TIME FORMAT
DATE=$(date +"%m_%d_%Y_%H_%M_%S")

# BACKUP FOLDER NAME
BAK_FOLDER="${PROJ_NAME}-${DATE}"

mkdir $BAK_FOLDER
cp -rf $PROJ_FOLDER ./$BAK_FOLDER/

echo "Backup folder: ${BAK_FOLDER} is created!"
sleep 2
